spring:
  application:
    name: Library

  datasource:
    url: jdbc:mysql://localhost:3306/tuneBox
    username: root
    password: pass@2024
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 28392767205-kjh3koov94lcf8d2dhh83o15siro23m7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: tuneboxvietnam@gmail.com
    password: znuo qxwy kjtd xmqz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: dslm1fjny
  api-key: 687813197331129
  api-secret: tGla5A5ZY2Jqp24sfTHtEN1ATds

server:
  port: 8083
